export const products = [
  {
    id: 1,
    stickerNew: "active",
    stickerAction: "active",
    stickerHit: "active",
    have: "active",
    notHave: "",
    img: "./img/catalog-cart/1.png",
    name: "Demm Rory Смеситель для биде на 1 отв. с донным клапаном, цвет: бронза",
    article: "Артикул: 47123CDn",
    collection: "Коллекция: ERYOS",
    price: "active",
    currentPrice: 45220,
    oldPrice: 54600,
    btnBasket: "",
    btnCounter: "disabled",
  },
  {
    id: 2,
    stickerNew: "",
    stickerAction: "",
    stickerHit: "",
    have: "active",
    notHave: "",
    img: "./img/catalog-cart/2.png",
    name: "Demm Rory Смеситель для раковины настенный скрытого монтажа, излив 18 см, цвет: хром",
    article: "Артикул: 4990X",
    collection: "Коллекция: KUOVADIS",
    price: "",
    currentPrice: 30120,
    oldPrice: 54600,
    btnBasket: "",
    btnCounter: "disabled",
  },
  {
    id: 3,
    stickerNew: "",
    stickerAction: "active",
    stickerHit: "",
    have: "",
    notHave: "active",
    img: "./img/catalog-cart/3.png",
    name: "Demm Rory Смеситель для раковины настенный скрытого монтажа, излив 18 см, цвет: хром",
    article: "Артикул: 44220X",
    collection: "Коллекция: JAGO",
    price: "active",
    currentPrice: 56220,
    oldPrice: 74600,
    btnBasket: "",
    btnCounter: "disabled",
  },
  {
    id: 4,
    stickerNew: "active",
    stickerAction: "",
    stickerHit: "",
    have: "active",
    notHave: "",
    img: "./img/catalog-cart/4.png",
    name: "Demm Rory Смеситель для раковины на 1 отв. с донным клапаном, цвет: хром",
    article: "Артикул: 47123CDn",
    collection: "Коллекция: JAGO",
    price: "",
    currentPrice: 26220,
    oldPrice: 54600,
    btnBasket: "",
    btnCounter: "disabled",
  },
  {
    id: 5,
    stickerNew: "",
    stickerAction: "active",
    stickerHit: "active",
    have: "active",
    notHave: "",
    img: "./img/catalog-cart/5.png",
    name: "Demm Rory Смеситель для биде на 1 отв. с донным клапаном, цвет: черный матовый",
    article: "Артикул: 47123CDn",
    collection: "Коллекция: JAGO",
    price: "active",
    currentPrice: 35400,
    oldPrice: 44600,
    btnBasket: "",
    btnCounter: "disabled",
  },
  {
    id: 6,
    stickerNew: "",
    stickerAction: "",
    stickerHit: "",
    have: "",
    notHave: "active",
    img: "./img/catalog-cart/6.png",
    name: "Demm Rory Смеситель для раковины на 1 отв, цвет: хром",
    article: "Артикул: 47123CDn",
    collection: "Коллекция: KUOVADIS",
    price: "",
    currentPrice: 45220,
    oldPrice: 54600,
    btnBasket: "",
    btnCounter: "disabled",
  },
  {
    id: 7,
    stickerNew: "",
    stickerAction: "",
    stickerHit: "active",
    have: "active",
    notHave: "",
    img: "./img/catalog-cart/7.png",
    name: "Demm Rory Смеситель для раковины на 1 отв, цвет: хром",
    article: "Артикул: 47123CDn",
    collection: "Коллекция: ERYOS",
    price: "",
    currentPrice: 15220,
    oldPrice: 54600,
    btnBasket: "",
    btnCounter: "disabled",
  },
  {
    id: 8,
    stickerNew: "",
    stickerAction: "",
    stickerHit: "",
    have: "",
    notHave: "active",
    img: "./img/catalog-cart/8.png",
    name: "Demm Rory Смеситель для раковины, излив 18 см, цвет: хром",
    article: "Артикул: 4990X",
    collection: "Коллекция: ERYOS",
    price: "",
    currentPrice: 45220,
    oldPrice: 54600,
    btnBasket: "",
    btnCounter: "disabled",
  },
  {
    id: 9,
    stickerNew: "",
    stickerAction: "",
    stickerHit: "",
    have: "active",
    notHave: "",
    img: "./img/catalog-cart/9.png",
    name: "Demm Rory Смеситель для раковины, излив 18 см, цвет: хром",
    article: "Артикул: 47123CDn",
    collection: "Коллекция: KUOVADIS",
    price: "",
    currentPrice: 25220,
    oldPrice: 54600,
    btnBasket: "",
    btnCounter: "disabled",
  },
  {
    id: 10,
    stickerNew: "active",
    stickerAction: "",
    stickerHit: "",
    have: "active",
    notHave: "",
    img: "./img/catalog-cart/4.png",
    name: "DDemm Rory Смеситель для раковины на 1 отв. с донным клапаном, цвет: хром",
    article: "Артикул: 49490X",
    collection: "Коллекция: JAGO",
    price: "",
    currentPrice: 26220,
    oldPrice: 54600,
    btnBasket: "",
    btnCounter: "disabled",
  },
  {
    id: 11,
    stickerNew: "",
    stickerAction: "active",
    stickerHit: "active",
    have: "active",
    notHave: "",
    img: "./img/catalog-cart/5.png",
    name: "Demm Rory Смеситель для биде на 1 отв. с донным клапаном, цвет: черный матовый",
    article: "Артикул: 49490X",
    collection: "Коллекция: JAGO",
    currentPrice: 35400,
    price: "active",
    oldPrice: 44600,
    btnBasket: "",
    btnCounter: "disabled",
  },
  {
    id: 12,
    stickerNew: "",
    stickerAction: "",
    stickerHit: "",
    have: "active",
    notHave: "",
    img: "./img/catalog-cart/6.png",
    name: "Demm Rory Смеситель для раковины на 1 отв, цвет: хром",
    article: "Артикул: 47123CDn",
    collection: "Коллекция: KUOVADIS",
    price: "",
    currentPrice: 45220,
    oldPrice: 54600,
    btnBasket: "",
    btnCounter: "disabled",
  },
];
